version: "3.9"

services:
  web:
    build: .
    container_name: lead_manager_web
    # command: bash -c "
    #   python manage.py migrate &&
    #   python manage.py runserver 0.0.0.0:8000
    #   "
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: lead_manager_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lead_tracker
      POSTGRES_USER: lead_user
      POSTGRES_PASSWORD: lead_pass

  test:
    build: .
    command: pytest --disable-warnings --tb=short -v
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
  media_data:
  static_data:
